trigger: ["master"]
pr: ["master"]

jobs:
# Check formatting
- template: ci/azure-rustfmt.yml
  parameters:
    name: rustfmt

- job: test_stable
  displayName: Test Stable
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-16.04
      MacOS:
        vmImage: macOS-10.13
      Windows:
        vmImage: vs2017-win2016
  pool:
    vmImage: $(vmImage)
  steps:
    - template: ci/azure-install-rust.yml
      parameters:
        rust_version: stable
    - script: cargo test --all --all-features
      displayName: cargo test --all --all-features
