[package]
authors = ["Lucio Franco <luciofranco14@gmail.com>"]
edition = "2018"
name = "tokio-bincode"
version = "0.1.0"

[dependencies]
bytes = "0.4"
bincode = "1.0"
tokio-codec = "0.1"
serde = "1.0"

[dev-dependencies]
tokio = "0.1"
futures = "0.1"
serde_derive = "1.0"

