name: Clippy

on: [push, pull_request]

jobs:
  clippy:
    runs-on: [self-hosted, rust]
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2020-08-23
        profile: minimal
        components: clippy
        override: true

    - name: Annotate commits
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets --all-features
